{% set version = "190600_20161030" %}

package:
  name: portaudio
  version: 19.6.0

source:
  url: http://www.portaudio.com/archives/pa_stable_v{{ version }}.tgz
  sha256: f5a21d7dcd6ee84397446fa1fa1a0675bb2e8a4a6dceb4305a8404698d8d1513
  patches:
    - disable-werror-macos.patch  # [osx]
    - empty-target-postfix.patch

build:
  number: 4
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - {{ cdt('alsa-lib-devel') }}  # [linux]
    - make                         # [unix]
  host:
    - alsa-lib  # [linux]
  run:
    - alsa-lib  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libportaudio$SHLIB_EXT  # [not win]
    - test -f $PREFIX/include/portaudio.h  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - if not exist %PREFIX%\\Library\\include\\portaudio.h exit 1  # [win]
    - if not exist $PREFIX$\\Library\\lib\\portaudio.lib exit 1  # [win]
    - if not exist $PREFIX$\\Library\\bin\\portaudio.dll exit 1  # [win]

about:
  home: http://www.portaudio.com/
  license: MIT
  license_file: LICENSE.txt
  summary: 'PortAudio is a free, cross-platform, open-source, audio I/O library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
    - traversaro
