{% set version = "190700_20210406" %}
{% set name = "portaudio" %}

package:
  name: {{ name }}
  version: 19.7.0

source:
  url: https://files.portaudio.com/archives/pa_stable_v{{ version }}.tgz
  sha256: 47efbf42c77c19a05d22e627d42873e991ec0c1357219c0d74ce6a2948cb2def
  patches:
    - disable-werror-macos.patch  # [osx]

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make  # [unix]
  host:
    - alsa-lib  # [linux]
  run:
    - alsa-lib  # [linux]

test:
  commands:
    - test -f $PREFIX/lib/libportaudio$SHLIB_EXT  # [not win]
    - test -f $PREFIX/include/portaudio.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\portaudio.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\portaudio.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\portaudio.dll exit 1  # [win]

about:
  home: http://www.portaudio.com/
  license: MIT
  license_file: LICENSE.txt
  summary: 'PortAudio is a free, cross-platform, open-source, audio I/O library.'

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
    - traversaro
