travis:
  secure:
    BINSTAR_TOKEN: QQd9xA4QSM5+u4Avkro7fxY0qfKmn4soI/QQ2e/DM0v/ZPisrVziU7ryLmSRJy38nEimWUvcRa5LEwW+mULc6FdEVIxR5LWoDP9R82u1GRgv8mXh/rgRjHAysaBCdb+4EbjDEtZqYWyc3rMTvxFOVa4SFnjoC4A/NkI9otE37FiuI6xV2AULMDslu/j9nfnMmsw4UnEIxjAZyby4DiW7jy27r0awsfXIb/95KE7KBtBaXu0StFJErDu1pTudtBZGsqNdBA6GKCVVsDmB7Z0f12c4APMf73mkaUfKBf62Nvz9EIz7C5ZUL2yDtLQe4bo04upcAfIyl1471Ptt8YTnSTlxXvetdsmk918sco1JlGSyqolpQyWDipA9t0eqfoTJmhL9V/6syAnShxfpiUcMWldTiyU2xTmL/mCBXCeDy+pa0bXW2xMc0auedWp4nT7DdpkLYreYRLmdFndrWIqxePcgveGsgBbepcXdNLG/zWorTeZTk24X05ezXC9fnVU7EnAUj3sTgpvKMsFGjcTc9vLYAQtFLjBF14zHE9WqqznMkz4XHJNtZdajo8XkCgAvTnhDdVuGbhJsRqBtWq3OtQb5fU8hCrDKiS3EE54aCteb11OpMTEVbrQvx9QXX4RoNK9H45tpEK9IDMvXGMnh0QjizJDhZKc67Uj9hguRggI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
